site_name: My Docs
theme:
  name: material

extra_css:
  - css/extra.css
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: list
            line_length: 92
            show_root_heading: true