site_name: Flashcard documentation
site_description: required. Used as feed mandatory channel description.
site_url: http://google.com
theme:
    name: material
plugins:
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 