site_name: My Docs
theme:
  name: material
  custom_dir: theme
  custom_templates:
    - custom.html
extra_css:
  - css/extra.css
extra_javascript:
  - js/test.js
  - https://code.jquery.com/jquery-3.6.0.min.js

